#!/bin/bash
# AYN Odin 3 — Create ROM and BIOS folder structure
# Run this in Termux: bash create_folders.sh

BASE="/storage/emulated/0"

echo "📁 Creating ROM folders..."
mkdir -p "$BASE/Roms/PS1"
mkdir -p "$BASE/Roms/PS2"
mkdir -p "$BASE/Roms/NDS"
mkdir -p "$BASE/Roms/SNES"
mkdir -p "$BASE/Roms/GBA"
mkdir -p "$BASE/Roms/GBC"
mkdir -p "$BASE/Roms/N64"
mkdir -p "$BASE/Roms/PSP"
mkdir -p "$BASE/Roms/Genesis"
mkdir -p "$BASE/Roms/NES"

echo "📁 Creating BIOS folders..."
mkdir -p "$BASE/BIOS/PS1"
mkdir -p "$BASE/BIOS/PS2"
mkdir -p "$BASE/BIOS/NDS"

echo ""
echo "✅ Done! Folder structure:"
echo ""
echo "$BASE/"
echo "├── Roms/"
echo "│   ├── PS1/"
echo "│   ├── PS2/"
echo "│   ├── NDS/"
echo "│   ├── SNES/"
echo "│   ├── GBA/"
echo "│   ├── GBC/"
echo "│   ├── N64/"
echo "│   ├── PSP/"
echo "│   ├── Genesis/"
echo "│   └── NES/"
echo "└── BIOS/"
echo "    ├── PS1/   ← scph5501.bin etc"
echo "    ├── PS2/   ← ps2 bios dump"
echo "    └── NDS/   ← bios7.bin bios9.bin firmware.bin"
echo ""
echo "Now drop your ROMs and BIOS files into the right folders!"
